name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  UV_VERSION: 0.9.0
  UV_NO_SYNC: 1
  UV_LOCKED: 1
  PY_COLORS: 1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Setup uv
        uses: astral-sh/setup-uv@eb1897b8dc4b5d5bfe39a428a8f2304605e0983c  # v7.0.0
        with:
          version: ${{ env.UV_VERSION }}
      - name: Environment
        id: sync
        run: uv sync
      - name: taplo (TOML formatting)
        if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
        run: uv run taplo fmt --check --diff pyproject.toml
      - name: ruff format
        if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
        run: uv run ruff format --diff
      - name: ruff lint
        if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
        run: uv run ruff check --output-format github
      - name: basedpyright
        if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
        run: uv run basedpyright app
